In [3]:
import numpy as np
from scipy.sparse import diags

In [2]:


def pairwise_differences(x):
    n = len(x)
    D = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            D[i, j] = x[i] - x[j]
    return D

# Example usage:
x = np.array([1, 2, 3, 4])
D = pairwise_differences(x)
print(D)


[[ 0. -1. -2. -3.]
 [ 1.  0. -1. -2.]
 [ 2.  1.  0. -1.]
 [ 3.  2.  1.  0.]]


In [5]:
# Function to calculate pairwise differences
def pairwise_differences(x):
    n = len(x)
    D = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(n):
            D[i, j] = x[i] - x[j]
    return D

In [6]:

# Define your 1D numpy array x
x = np.linspace(0, 2 * np.pi, 1000)

# Calculate pairwise differences using the provided function
D_pairwise = pairwise_differences(x)

In [7]:
D_pairwise

array([[ 0.        , -0.00628947, -0.01257895, ..., -6.27060636,
        -6.27689583, -6.28318531],
       [ 0.00628947,  0.        , -0.00628947, ..., -6.26431688,
        -6.27060636, -6.27689583],
       [ 0.01257895,  0.00628947,  0.        , ..., -6.25802741,
        -6.26431688, -6.27060636],
       ...,
       [ 6.27060636,  6.26431688,  6.25802741, ...,  0.        ,
        -0.00628947, -0.01257895],
       [ 6.27689583,  6.27060636,  6.26431688, ...,  0.00628947,
         0.        , -0.00628947],
       [ 6.28318531,  6.27689583,  6.27060636, ...,  0.01257895,
         0.00628947,  0.        ]])

In [8]:
# Create a sparse differentiation matrix (e.g., finite difference)
n = len(x)
h = x[1] - x[0]
diff_matrix = diags([1, -1], [0, 1], (n-1, n)) / h

# Apply the sparse differentiation matrix to x
x_diff = diff_matrix.dot(x)

In [9]:
x_diff

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1

In [10]:



# Measure performance gains (for comparison purposes)
import time
start_time = time.time()
for _ in range(1000):
    x_diff = diff_matrix.dot(x)
end_time = time.time()
print("Time taken:", end_time - start_time)


Time taken: 0.016494035720825195
