In [13]:
import numpy as np
import timeit
from scipy.linalg import qr, svd

#Task 1: You have seen that the SVD of an m × n matrix A gives, among other things,a basis for the range (column space). Compute this for the given matrix.


In [2]:
# Define the matrix A
A = np.array([[1, -2, 3, -3],
              [2, -4, 9, -2],
              [-3, 6, -9, 9]])

In [3]:
# Compute the SVD of A
U, S, Vt = svd(A)

In [4]:

# Extract the columns of U corresponding to nonzero singular values
nonzero_singular_values_indices = np.where(S > 1e-10)[0]
column_basis = U[:, nonzero_singular_values_indices]

# Display the basis for the column space
print("Basis for the column space (range) of A:")
print(column_basis)


Basis for the column space (range) of A:
[[ 0.26623586  0.17064134]
 [ 0.5396153  -0.84191171]
 [-0.79870758 -0.51192403]]


In [8]:

# Step 1: Compute the QR factorization of A
Q, R = qr(A, mode='economic')

# Step 2: Extract the columns of Q corresponding to the pivot columns of R
# Find pivot columns by identifying nonzero elements on the diagonal of R
pivot_columns = np.where(np.abs(np.diag(R)) > 1e-10)[0]
column_basis_qr = Q[:, pivot_columns]

# Step 3: Compute the SVD of A
U, S, Vt = svd(A)

# Step 4: Extract the columns of U corresponding to nonzero singular values
nonzero_singular_values_indices = np.where(S > 1e-10)[0]
column_basis_svd = U[:, nonzero_singular_values_indices]

# Display the basis obtained using QR and SVD
print("Basis for the column space (range) of A using QR:")
print(column_basis_qr)

print("\nBasis for the column space (range) of A using SVD:")
print(column_basis_svd)

# Compare the two bases (they should be equivalent)
if np.allclose(column_basis_qr, column_basis_svd):
    print("\nThe bases obtained using QR and SVD are equivalent.")
else:
    print("\nThe bases obtained using QR and SVD are not equivalent.")


Basis for the column space (range) of A using QR:
[[-0.26726124 -0.11952286]
 [-0.53452248  0.84401323]
 [ 0.80178373  0.52283453]]

Basis for the column space (range) of A using SVD:
[[ 0.26623586  0.17064134]
 [ 0.5396153  -0.84191171]
 [-0.79870758 -0.51192403]]

The bases obtained using QR and SVD are not equivalent.


# Task 2: Check that the column spaces (not the bases) you obtained in the two ways are the same. (How would you check that two given bases span the same space?)


In [11]:

# Step 5: Check if the column spaces are the same

# Check if the column space spanned by column_basis_qr is also spanned by column_basis_svd
qr_space_in_svd = np.all(np.isin(column_basis_qr, column_basis_svd))

# Check if the column space spanned by column_basis_svd is also spanned by column_basis_qr
svd_space_in_qr = np.all(np.isin(column_basis_svd, column_basis_qr))

# Check if both checks are True (i.e., the column spaces are the same)
if qr_space_in_svd and svd_space_in_qr:
    print("The column spaces obtained using QR and SVD are the same.")
else:
    print("The column spaces obtained using QR and SVD are not the same.")


The column spaces obtained using QR and SVD are not the same.


# Task 3: For a 500 × 500 random matrix, which method is faster?

In [15]:

# Generate a random 500x500 matrix
random_matrix = np.random.rand(500, 500)

# Measure the execution time for the QR method
qr_time = timeit.timeit(lambda: get_basis_qr(random_matrix), number=10)

# Measure the execution time for the SVD method
svd_time = timeit.timeit(lambda: get_basis_svd(random_matrix), number=10)

# Compare the execution times
if qr_time < svd_time:
    print("QR method is faster.")
elif qr_time > svd_time:
    print("SVD method is faster.")
else:
    print("Both methods have similar execution times.")


QR method is faster.
